use std::time::Duration;

pub(crate) enum Reply {
    Inactive(&'static str),
    SlowDripInactive(&'static str, Duration, usize),
    Legacy(&'static str),
    Raw(Vec<u8>),
    RawThenStall(Vec<u8>),
    Retryable(&'static str),
    SubmissionFlow,
    WorkspacePresentSubmissionFlow,
    ResumableSubmissionFlow(u64),
    DelayedOutputSubmissionFlow(Duration),
    RemoteSubmissionFlow,
    EmptyRemoteSubmissionFlow,
    DelayedSubmissionFlow(&'static str, Duration),
    DelayedCancellationFlow(&'static str, Duration, &'static str),
    AttachCancellationFlow(Duration),
    FailedSubmissionFlow,
    RetrySubmissionFlow,
    ManagementFlow,
    DashboardAttachFlow,
    ExpiredDashboardAttachFlow,
    InteractiveDashboardFlow(Duration),
    InteractiveDashboardCancellationFlow(Duration),
    FailedAttachFlow,
    TerminalOutputFlow(&'static str, bool),
    PreflightConflictFlow(Duration),
    UnsafeOutputFlow,
    SymlinkChainOutputFlow,
    HugeOutputFlow,
    Close,
    Success,
}
