MACHINE: str
USER: str
PROJECT: str
WORKTREE: str
DURING: str
AT_START: str
FIFO: str
PRIORITY: str

def module_spec(tasks: list, limiters: list | None = ..., queues: list | None = ..., exclude: list | None = ..., includes: list | None = ..., defaults: dict | None = ..., project_id: str | None = ...) -> dict: ...
def task(name: str, deps: list | str | dict | None = ..., steps: list | None = ..., needs: list | None = ..., queue: dict | None = ..., retry: dict | None = ..., timeout_s: int | None = ..., context: dict | None = ..., execution: dict | None = ..., tags: list | None = ..., doc: str | None = ...) -> dict: ...
def cmd(*argv: str, cwd: str | None = ..., env: dict | None = ...) -> dict: ...
def script(path: str, *argv: str, interpreter: str | None = ..., cwd: str | None = ..., env: dict | None = ...) -> dict: ...
def need(name: str, slots: float = ..., scope: str = ..., hold: str = ...) -> dict: ...
def queue_use(name: str, scope: str = ..., slots: int = ..., priority: int = ...) -> dict: ...
def resource(name: str, capacity: float, unit: str | None = ..., scope: str = ...) -> dict: ...
def lock(name: str, scope: str = ...) -> dict: ...
def queue_def(name: str, slots: int, discipline: str = ..., max_pending: int | None = ..., scope: str = ...) -> dict: ...
def rate_limit(name: str, burst: int, refill_per_second: float, scope: str = ...) -> dict: ...
def process_cap(name: str, max_running: int, match: str | None = ..., scope: str = ...) -> dict: ...
def retry(attempts: int = ..., on_exit: list | None = ..., backoff: dict | None = ...) -> dict: ...
def fixed(seconds: float) -> dict: ...
def exp_jitter(min_s: float = ..., max_s: float = ..., jitter: str = ...) -> dict: ...
def Local(id: str, max_parallel_tasks: int = ..., runtime: dict | None = ...) -> dict: ...
def Remote(pool: str | None = ..., required_tags: list | None = ..., required_capabilities: list | None = ..., transport: dict | None = ..., runtime: dict | None = ...) -> dict: ...
def AnyTransport() -> dict: ...
def ContainerRuntime(image: str, command: list | None = ..., mounts: list | None = ..., env: dict | None = ..., resources: dict | None = ...) -> dict: ...
def DockerfileRuntime(dockerfile: dict | str, build_context: dict | str | None = ..., command: list | None = ..., mounts: list | None = ..., env: dict | None = ..., resources: dict | None = ...) -> dict: ...
def LocalOnly(local: dict) -> dict: ...
def RemoteOnly(remote: dict) -> dict: ...
def ByCustomPolicy(policy: object) -> dict: ...
def path(value: str) -> dict: ...
def gitignore() -> dict: ...
def CurrentState(roots: list | None = ..., ignored: list | None = ..., include: list | None = ...) -> dict: ...
