#![recursion_limit = "256"]

pub mod support;

mod client_execution_architecture_contract;
mod container_runtime_bollard_contract;
mod doctest_policy_contract;
mod module_layout_contract;
mod public_exec_api_contract;
mod remote_worker_container_cleanup_behavior;
mod remote_worker_container_user_behavior;
mod remote_worker_environment_contract;
#[path = "remote_worker_runtime_behavior.rs"]
mod remote_worker_runtime_behavior;
mod remote_worker_runtime_failure_behavior;
mod remote_worker_runtime_nonzero_exit_behavior;
mod remote_worker_runtime_oom_behavior;
mod remote_worker_runtime_streaming_behavior;
mod retired_client_surface_architecture_contract;
mod sqlite_connection_lifecycle_contract;
mod timeout_deadline_precedence_behavior;
mod unix_socket_bind_path_contract;
